env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=G94J8nYSDywCFdXoSKke4WTlZSOjGyuol

addons:
language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8
  
  addons:
  apt:
  packages:
  - oracle-java8-installer

after_success:
  - gradle jacocoTestReport coveralls
