env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=G94J8nYSDywCFdXoSKke4WTlZSOjGyuol
    
language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
